[features]
seeds = false
skip-lint = false
[programs.localnet]
rivalz_goalflip = "AfkTvJCbHWTYwrsxVqVW7sxTbgp561ExzrzXS6BuLqQT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "<YOUR_KEYPAIR_JSON>"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
